[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
    "--ignore=data",
]

pythonpath = [
  "."
]

[tool.pylint.main]
indent-string="    " # this means 4 spaces

disable=[
  "missing-module-docstring",
  "missing-function-docstring",
  "relative-beyond-top-level", # we already know that our imports are completely broken
  "import-error", # as above
  "too-many-locals", # seems unhelpful idk
  "invalid-name" # this rule enforces snake_case
]

load-plugins = "pylint_actions"

[tool.pyright]
exclude=["**/data"]
